In [1]:
import tensorflow as tf
import numpy as np

In [3]:
!nvcc --version

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2024 NVIDIA Corporation
Built on Thu_Jun__6_02:18:23_PDT_2024
Cuda compilation tools, release 12.5, V12.5.82
Build cuda_12.5.r12.5/compiler.34385749_0


In [2]:
print(tf.__version__)

2.19.0


In [ ]:
scaler = tf.constant(7)

In [4]:
scaler

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [5]:
type(scaler)

tensorflow.python.framework.ops.EagerTensor

In [ ]:
scaler.ndim

0

In [ ]:
vector = tf.constant([1,2])

In [ ]:
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2], dtype=int32)>

In [ ]:
vector.shape

TensorShape([2])

In [10]:
vector.ndim

1

In [ ]:
type(vector)

tensorflow.python.framework.ops.EagerTensor

In [12]:
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2], dtype=int32)>

In [13]:
matrix = tf.constant(
    [
        [1,2],
        [3,4]
    ]
)

In [14]:
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [ ]:
matrix.ndim

2

In [16]:
matrix_2 = tf.constant([
    [1.0,4.0],
    [2.3,5.6]
],dtype=tf.float16)

In [ ]:
matrix_2

<tf.Tensor: shape=(2, 2), dtype=float16, numpy=
array([[1. , 4. ],
       [2.3, 5.6]], dtype=float16)>

In [ ]:
TENSOR = tf.constant([
    [
        [1,2,3],
        [4,5,6],
        [1,2,3],
        [4,5,6]
    ],
    [
        [7,8,9],
        [10,11,12],
        [7,8,9],
        [10,11,12]
    ],
    [
        [7,8,9],
        [10,11,12],
        [7,8,9],
        [10,11,12]
    ],
    [
        [7,8,9],
        [10,11,12],
        [7,8,9],
        [10,11,12]
    ]
])

In [19]:
TENSOR.shape

TensorShape([4, 4, 3])

In [ ]:
TENSOR

<tf.Tensor: shape=(4, 4, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[ 7,  8,  9],
        [10, 11, 12],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[ 7,  8,  9],
        [10, 11, 12],
        [ 7,  8,  9],
        [10, 11, 12]]], dtype=int32)>

In [21]:
TENSOR.ndim

3

In [22]:
unchange_tensor = tf.constant([1,2])
change_tensor = tf.Variable([1,2,3])

In [ ]:
change_tensor

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

In [ ]:
unchange_tensor

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2], dtype=int32)>

In [ ]:
change_tensor[0]

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [26]:
change_tensor[0].assign(10)

<tf.Variable 'UnreadVariable' shape=(3,) dtype=int32, numpy=array([10,  2,  3], dtype=int32)>

In [27]:
change_tensor[2].assign(20)

<tf.Variable 'UnreadVariable' shape=(3,) dtype=int32, numpy=array([10,  2, 20], dtype=int32)>

In [28]:
change_tensor.shape

TensorShape([3])

In [29]:
type(change_tensor)

tensorflow.python.ops.resource_variable_ops.ResourceVariable

In [30]:
change_tensor.shape

TensorShape([3])

In [31]:
random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal(shape=(3, 2))

random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3, 2))

random_1, random_2, random_1==random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

In [ ]:
random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal(shape=(3, 2))

random_2 = tf.random.Generator.from_seed(11)
random_2 = random_2.normal(shape=(3, 2))

random_1, random_2, random_1==random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ 0.27305737, -0.29925638],
        [-0.3652325 ,  0.61883307],
        [-1.0130816 ,  0.28291714]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[False, False],
        [False, False],
        [False, False]])>)

In [ ]:
tf.reduce_max(random_1),tf.reduce_min(random_1)

(<tf.Tensor: shape=(), dtype=float32, numpy=0.0759502574801445>,
 <tf.Tensor: shape=(), dtype=float32, numpy=-1.8107855319976807>)

In [34]:
tf.reduce_max(random_2),tf.reduce_min(random_2)

(<tf.Tensor: shape=(), dtype=float32, numpy=0.618833065032959>,
 <tf.Tensor: shape=(), dtype=float32, numpy=-1.0130815505981445>)

In [35]:
random_3 = tf.random.Generator.from_seed(42)
random_3 = random_3.normal(shape=(3, 2))

random_4 = tf.random.Generator.from_seed(11)
random_4 = random_4.normal(shape=(3,2))

random_3, random_4, random_3 == random_4

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ 0.27305737, -0.29925638],
        [-0.3652325 ,  0.61883307],
        [-1.0130816 ,  0.28291714]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[False, False],
        [False, False],
        [False, False]])>)

In [ ]:
random_1 == random_3

<tf.Tensor: shape=(3, 2), dtype=bool, numpy=
array([[ True,  True],
       [ True,  True],
       [ True,  True]])>

In [37]:
not_shuffled = tf.constant(
    [
        [1, 2],
        [3, 4],
        [5, 6]
    ]
)
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)>

In [38]:
a = tf.random.shuffle(not_shuffled, seed=42)

In [39]:
a

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[5, 6],
       [3, 4],
       [1, 2]], dtype=int32)>

In [40]:
# tf.random.set_seed(42)
tf.random.shuffle(not_shuffled, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[5, 6],
       [3, 4],
       [1, 2]], dtype=int32)>

In [41]:
ones_tensor = tf.ones(shape=(5, 3))

In [42]:
ones_tensor

<tf.Tensor: shape=(5, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [43]:
zeros_tensor = tf.zeros(shape=(5, 3))

In [44]:
zeros_tensor

<tf.Tensor: shape=(5, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [45]:
array_np = np.arange(1,3)

In [46]:
array_np

array([1, 2])

In [47]:
tensor_array = tf.constant(array_np,shape=(1,2))

In [48]:
tensor_array

<tf.Tensor: shape=(1, 2), dtype=int64, numpy=array([[1, 2]])>

In [49]:
type(tensor_array)

tensorflow.python.framework.ops.EagerTensor

In [50]:
tensor_array.ndim

2

In [51]:
zeros_tensor.shape

TensorShape([5, 3])

In [52]:
zeros_tensor.ndim

2

In [53]:
tf.size(zeros_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=15>

In [54]:
tensor = tf.ones(shape=(2, 2, 2, 2))

In [55]:
tensor[:1,:1,:1,:1]

<tf.Tensor: shape=(1, 1, 1, 1), dtype=float32, numpy=array([[[[1.]]]], dtype=float32)>

In [56]:
rank_2_tensor = tf.constant(
    [
        [10, 7],
        [3, 4]
    ]
)

In [57]:
rank_2_tensor[1,:]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 4], dtype=int32)>

In [58]:
rank_3_tensor = rank_2_tensor[...,tf.newaxis]

In [59]:
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [60]:
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [61]:
rank_4_tensor = rank_3_tensor[..., tf.newaxis]

In [62]:
rank_4_tensor

<tf.Tensor: shape=(2, 2, 1, 1), dtype=int32, numpy=
array([[[[10]],

        [[ 7]]],


       [[[ 3]],

        [[ 4]]]], dtype=int32)>

In [63]:
rank_4_tensor.ndim

4

In [64]:
tf.expand_dims(rank_4_tensor, axis=1)

<tf.Tensor: shape=(2, 1, 2, 1, 1), dtype=int32, numpy=
array([[[[[10]],

         [[ 7]]]],



       [[[[ 3]],

         [[ 4]]]]], dtype=int32)>

In [65]:
tensor = tf.constant(
    [
        [1, 2],
        [3, 4]
    ]
)

In [66]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [67]:
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[11, 12],
       [13, 14]], dtype=int32)>

In [68]:
tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 20],
       [30, 40]], dtype=int32)>

In [69]:
tensor / 5

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[0.2, 0.4],
       [0.6, 0.8]])>

In [70]:
tensor - 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[-9, -8],
       [-7, -6]], dtype=int32)>

In [71]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [72]:
tensor_2 = tf.constant(
    [
        [2, 4],
        [6, 8]
    ]
)

In [73]:
tensor_2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 4],
       [6, 8]], dtype=int32)>

In [74]:
tf.add(tensor, tensor_2)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 3,  6],
       [ 9, 12]], dtype=int32)>

In [75]:
tf.multiply(tensor, tensor_2)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 2,  8],
       [18, 32]], dtype=int32)>

In [76]:
tf.divide(tensor_2, tensor)

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[2., 2.],
       [2., 2.]])>

In [77]:
tensor @ tensor_2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[14, 20],
       [30, 44]], dtype=int32)>

In [78]:
tensor,tensor_2

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[2, 4],
        [6, 8]], dtype=int32)>)

In [79]:
tf.matmul(tensor, tensor_2)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[14, 20],
       [30, 44]], dtype=int32)>

In [80]:
tf.multiply(tensor, tensor_2)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 2,  8],
       [18, 32]], dtype=int32)>

In [81]:
tf.reshape(tensor=tensor_2,shape=(1,4))

<tf.Tensor: shape=(1, 4), dtype=int32, numpy=array([[2, 4, 6, 8]], dtype=int32)>

In [82]:
tensor.shape

TensorShape([2, 2])

In [83]:
tensor_2.shape

TensorShape([2, 2])

In [84]:
tensor_3 = tf.Variable([[1,2],[3,4]])

In [85]:
tensor_3.shape

TensorShape([2, 2])

In [86]:
tensor_3 = tf.reshape(tensor_3,[-1])

In [87]:
tensor_3.shape

TensorShape([4])

In [88]:
tensor_3

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [89]:
tensor_2.shape,tensor_3.shape

(TensorShape([2, 2]), TensorShape([4]))

In [ ]:
# tensor_2 @ tensor_3

InvalidArgumentError: {{function_node __wrapped__MatMul_device_/job:localhost/replica:0/task:0/device:CPU:0}} In[0] and In[1] has different ndims: [2,2] vs. [4] [Op:MatMul] name: 

In [91]:
tensor_2 = tf.reshape(tensor_2,[-1])

In [92]:
tensor_2 = tf.constant([[1,2],[1,2]])

In [93]:
tensor_3 = tf.constant([[3],[4]])

In [94]:
tensor_2,tensor_3

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[1, 2],
        [1, 2]], dtype=int32)>,
 <tf.Tensor: shape=(2, 1), dtype=int32, numpy=
 array([[3],
        [4]], dtype=int32)>)

In [95]:
tf.matmul(tensor_2,tensor_3)

<tf.Tensor: shape=(2, 1), dtype=int32, numpy=
array([[11],
       [11]], dtype=int32)>

In [96]:
tensor_3

<tf.Tensor: shape=(2, 1), dtype=int32, numpy=
array([[3],
       [4]], dtype=int32)>

In [97]:
tensor_3 = tf.transpose(tensor_3)

In [98]:
tensor_3

<tf.Tensor: shape=(1, 2), dtype=int32, numpy=array([[3, 4]], dtype=int32)>

In [99]:
tensor_5 = tf.constant(
    [
        [1, 2],
        [3, 4],
        [5, 6]
    ]
)
tensor_6 = tf.constant(
    [
        [7, 8],
        [9, 10],
        [11, 12],
        [13, 14]
    ]
)

In [100]:
tensor_5.shape,tensor_6.shape

(TensorShape([3, 2]), TensorShape([4, 2]))

In [101]:
tf.matmul(
    a=tensor_5, b=tensor_6,
    transpose_a =False, transpose_b=True
)

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[ 23,  29,  35,  41],
       [ 53,  67,  81,  95],
       [ 83, 105, 127, 149]], dtype=int32)>

In [108]:
X = tf.constant(
    [[1,2,3],
    [4,5,6]]
)
Y = tf.constant(
    [
        [7,8,9],
        [10,11,12],
    ]
)

In [109]:
type(X),type(Y)

(tensorflow.python.framework.ops.EagerTensor,
 tensorflow.python.framework.ops.EagerTensor)

In [112]:
X @ tf.transpose(Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 50,  68],
       [122, 167]], dtype=int32)>

In [114]:
X,tf.transpose(Y)

(<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7, 10],
        [ 8, 11],
        [ 9, 12]], dtype=int32)>)

In [116]:
Y.shape

TensorShape([2, 3])

In [119]:
Y

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7,  8,  9],
       [10, 11, 12]], dtype=int32)>

In [118]:
tf.reshape(Y,(3,2))

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 7,  8],
       [ 9, 10],
       [11, 12]], dtype=int32)>

In [120]:
tf.transpose(Y)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 7, 10],
       [ 8, 11],
       [ 9, 12]], dtype=int32)>

In [121]:
Y = tf.constant(
    [
        [7,8,9],
        [10,11,12],
    ]
)

In [122]:
tf.transpose(Y)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 7, 10],
       [ 8, 11],
       [ 9, 12]], dtype=int32)>

In [123]:
float_tensor = tf.constant([1.7,2.4])

In [124]:
float_tensor

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1.7, 2.4], dtype=float32)>

In [125]:
int_tensor = tf.constant([1,2])

In [126]:
int_tensor

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2], dtype=int32)>

In [128]:
float_tensor = tf.cast(int_tensor, dtype=tf.float64)

In [130]:
print(float_tensor)

tf.Tensor([1. 2.], shape=(2,), dtype=float64)


In [131]:
print(int_tensor)

tf.Tensor([1 2], shape=(2,), dtype=int32)


In [132]:
int_tensor = tf.cast(int_tensor, dtype=tf.float32)

In [133]:
print(int_tensor)

tf.Tensor([1. 2.], shape=(2,), dtype=float32)


In [134]:
neg_tensor = tf.constant([-1, -4])

In [136]:
print(tf.abs(neg_tensor))

tf.Tensor([1 4], shape=(2,), dtype=int32)


In [137]:
random_tensor = tf.constant(
    np.random.randint(low=0, high=1000, size=50)
)

In [139]:
random_tensor

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([869, 377, 606, 701, 694,  34, 898, 626, 236,  93, 796, 801, 313,
       848, 808, 172, 965, 774, 533, 612, 985,  65, 537,  63, 858,  48,
       564, 571, 605, 591, 236, 874, 673,  77, 991, 520, 557,   3, 184,
       439, 935, 370, 290, 946, 455,  47, 917, 185, 424, 460])>

In [140]:
tf.reduce_min(random_tensor)

<tf.Tensor: shape=(), dtype=int64, numpy=3>

In [141]:
tf.reduce_max(random_tensor)

<tf.Tensor: shape=(), dtype=int64, numpy=991>

In [142]:
tf.reduce_mean(random_tensor)

<tf.Tensor: shape=(), dtype=int64, numpy=524>

In [143]:
tf.reduce_sum(random_tensor)

<tf.Tensor: shape=(), dtype=int64, numpy=26226>

In [144]:
tf.reduce_prod(random_tensor)

<tf.Tensor: shape=(), dtype=int64, numpy=2768834161530634240>

In [145]:
tf.argmax(random_tensor)

<tf.Tensor: shape=(), dtype=int64, numpy=34>

In [146]:
tf.argmin(random_tensor)

<tf.Tensor: shape=(), dtype=int64, numpy=37>

In [153]:
a = tf.constant(np.random.randint(0,100,50),
shape = (1,1,1,50))

In [155]:
a.shape

TensorShape([1, 1, 1, 50])

In [158]:
a = tf.squeeze(a)

In [159]:
a.shape

TensorShape([50])

In [167]:
some_list = [0, 1, 2, 3, 4, 1]
tf.one_hot(some_list, depth=5)

<tf.Tensor: shape=(6, 5), dtype=float32, numpy=
array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 1., 0., 0., 0.]], dtype=float32)>

In [168]:
tf.one_hot(some_list, depth=4, on_value="Yes", off_value="No")

<tf.Tensor: shape=(6, 4), dtype=string, numpy=
array([[b'Yes', b'No', b'No', b'No'],
       [b'No', b'Yes', b'No', b'No'],
       [b'No', b'No', b'Yes', b'No'],
       [b'No', b'No', b'No', b'Yes'],
       [b'No', b'No', b'No', b'No'],
       [b'No', b'Yes', b'No', b'No']], dtype=object)>

In [175]:
a = tf.constant('a')

In [177]:
a.numpy().decode('utf-8')

'a'

In [184]:
n = tf.constant(np.arange(1,10))

In [185]:
n

<tf.Tensor: shape=(9,), dtype=int64, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9])>

In [186]:
tf.square(n)

<tf.Tensor: shape=(9,), dtype=int64, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])>

In [201]:
n = tf.cast(n, dtype=tf.float32)

In [190]:
tf.sqrt(n)

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.236068 , 2.4494898,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [195]:
n

<tf.Tensor: shape=(9,), dtype=float32, numpy=array([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float32)>

In [202]:
tf.math.log(n)

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

In [210]:
i = tf.Variable(np.arange(1,5))

In [211]:
i

<tf.Variable 'Variable:0' shape=(4,) dtype=int64, numpy=array([1, 2, 3, 4])>

In [214]:
i.assign([1, 2, 3, 5])

<tf.Variable 'UnreadVariable' shape=(4,) dtype=int64, numpy=array([1, 2, 3, 5])>

In [217]:
i.assign_add([20,20,20,1])

<tf.Variable 'UnreadVariable' shape=(4,) dtype=int64, numpy=array([21, 22, 23,  6])>

In [218]:
i

<tf.Variable 'Variable:0' shape=(4,) dtype=int64, numpy=array([21, 22, 23,  6])>

In [220]:
type(i)

tensorflow.python.ops.resource_variable_ops.ResourceVariable

In [221]:
i.numpy()

array([21, 22, 23,  6])

In [222]:
type(i)

tensorflow.python.ops.resource_variable_ops.ResourceVariable

In [223]:
np.array(i)

array([21, 22, 23,  6])

In [224]:
type(i)

tensorflow.python.ops.resource_variable_ops.ResourceVariable

In [225]:
type(i.numpy())

numpy.ndarray

In [228]:
i = np.array(i)

In [229]:
type(i)

numpy.ndarray

In [230]:
i

array([21, 22, 23,  6])

In [233]:
i = tf.convert_to_tensor(i)

In [235]:
type(i)

tensorflow.python.framework.ops.EagerTensor

In [236]:
j = tf.constant(np.array([1.1, 2.2]))
k = tf.constant([1.1, 2.2])

In [237]:
j.dtype, k.dtype

(tf.float64, tf.float32)

In [267]:
def print_mani(fun):
    print("mani")
    return fun

In [268]:
@print_mani
def print_sum():
    print("sum")

mani


In [269]:
print_sum()

sum


In [274]:
# Create a simple function
def function(x, y):
  return x ** 2 + y

x = tf.constant(np.arange(0, 10))
y = tf.constant(np.arange(10, 20))
function(x, y)

<tf.Tensor: shape=(10,), dtype=int64, numpy=array([ 10,  12,  16,  22,  30,  40,  52,  66,  82, 100])>

In [276]:
# Create a simple function
@tf.function
def function(x,y):
    return x ** 2 + y
function(x, y)

<tf.Tensor: shape=(10,), dtype=int64, numpy=array([ 10,  12,  16,  22,  30,  40,  52,  66,  82, 100])>

In [6]:
print(tf.config.list_physical_devices('GPU'))

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]


In [7]:
!nvidia-smi

Tue Nov 25 19:41:14 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   45C    P8             10W /   70W |       2MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [ ]:
Import

# Exercises

##### 1 - Create a vector, scalar, matrix and tensor with values of your choosing using tf.constant().

In [3]:
scalar = tf.constant(4)

In [4]:
scalar.ndim

0

In [5]:
vector = tf.constant([4])

In [6]:
vector.ndim

1

In [7]:
matrix = tf.constant([[4]])

In [8]:
matrix.ndim

2

In [9]:
tensor = tf.constant([[[1]]])

In [10]:
tensor.ndim

3

In [11]:
tensor.shape

TensorShape([1, 1, 1])

##### 2 - Find the shape, rank and size of the tensors you created in 1.

In [14]:
scalar.shape, vector.shape, tensor.shape

(TensorShape([]), TensorShape([1]), TensorShape([1, 1, 1]))

In [17]:
tf.size(scalar), tf.size(vector), tf.size(tensor)

(<tf.Tensor: shape=(), dtype=int32, numpy=1>,
 <tf.Tensor: shape=(), dtype=int32, numpy=1>,
 <tf.Tensor: shape=(), dtype=int32, numpy=1>)

In [18]:
scalar.ndim, vector.ndim, tensor.ndim

(0, 1, 3)

##### 3 - Create two tensors containing random values between 0 and 1 with shape [5, 300].

In [39]:
one_tensor = tf.constant(np.random.rand(5,300))
two_tensor = tf.constant(np.random.rand(5,300))

In [40]:
one_tensor, two_tensor

(<tf.Tensor: shape=(5, 300), dtype=float64, numpy=
 array([[0.84773806, 0.6004802 , 0.09282123, ..., 0.37946464, 0.49965777,
         0.64965325],
        [0.81566983, 0.07543913, 0.4159097 , ..., 0.19856501, 0.69049937,
         0.13129877],
        [0.64141344, 0.63370256, 0.65341743, ..., 0.2883642 , 0.47708351,
         0.07381765],
        [0.34970272, 0.89512513, 0.37677074, ..., 0.53740308, 0.33384435,
         0.41271468],
        [0.54750609, 0.62625138, 0.59124817, ..., 0.58118686, 0.25720892,
         0.2950589 ]])>,
 <tf.Tensor: shape=(5, 300), dtype=float64, numpy=
 array([[0.54192978, 0.34462038, 0.58205579, ..., 0.44647173, 0.47151618,
         0.62599661],
        [0.59809275, 0.33644773, 0.65164293, ..., 0.48770619, 0.86863557,
         0.51474111],
        [0.37502274, 0.4193756 , 0.95901635, ..., 0.82543098, 0.58766001,
         0.79164863],
        [0.35048756, 0.33978626, 0.37841857, ..., 0.22037774, 0.08599744,
         0.06957604],
        [0.10371691, 0.25205432

##### 4 - Multiply the two tensors you created in 3 using matrix multiplication.

In [42]:
one_tensor @ tf.transpose(two_tensor)

<tf.Tensor: shape=(5, 5), dtype=float64, numpy=
array([[74.8116439 , 74.99645076, 77.54376981, 74.26442722, 71.7676719 ],
       [74.85337531, 77.68687135, 75.67841621, 76.14320903, 76.35121194],
       [71.93643397, 71.57739308, 77.97230966, 73.34002584, 69.01258857],
       [73.71014467, 73.99517706, 77.91959612, 76.78656181, 72.24966689],
       [78.3660082 , 78.33513472, 80.63331811, 77.25440349, 76.02568442]])>

##### 5 - Multiply the two tensors you created in 3 using dot product.

In [48]:
tf.tensordot(
    one_tensor, tf.transpose(two_tensor),axes=1
)

<tf.Tensor: shape=(5, 5), dtype=float64, numpy=
array([[74.8116439 , 74.99645076, 77.54376981, 74.26442722, 71.7676719 ],
       [74.85337531, 77.68687135, 75.67841621, 76.14320903, 76.35121194],
       [71.93643397, 71.57739308, 77.97230966, 73.34002584, 69.01258857],
       [73.71014467, 73.99517706, 77.91959612, 76.78656181, 72.24966689],
       [78.3660082 , 78.33513472, 80.63331811, 77.25440349, 76.02568442]])>

##### 6 - Create a tensor with random values between 0 and 1 with shape [224, 224, 3].

In [63]:
one_zero = tf.random.uniform([224,224,3])

In [64]:
one_zero

<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[0.5314312 , 0.73713183, 0.63644874],
        [0.23904872, 0.3861333 , 0.58301544],
        [0.23394382, 0.17021883, 0.55063176],
        ...,
        [0.02167153, 0.7076198 , 0.8269985 ],
        [0.23766279, 0.6964278 , 0.88382304],
        [0.6927519 , 0.4496113 , 0.26040518]],

       [[0.06430519, 0.36265826, 0.37949812],
        [0.6759261 , 0.03981161, 0.9346136 ],
        [0.31190753, 0.11959481, 0.6718023 ],
        ...,
        [0.44657612, 0.57661283, 0.98230016],
        [0.7042577 , 0.11970222, 0.00414741],
        [0.9584907 , 0.71211874, 0.2022295 ]],

       [[0.43962753, 0.6592467 , 0.6856307 ],
        [0.47428024, 0.7737429 , 0.79511416],
        [0.34869432, 0.37740493, 0.26967633],
        ...,
        [0.73642707, 0.8775866 , 0.15585327],
        [0.63213885, 0.8936055 , 0.69404924],
        [0.23127377, 0.23349619, 0.57372904]],

       ...,

       [[0.46574545, 0.66658247, 0.93338096],
        [0.14

##### 7 - Find the min and max values of the tensor you created in 6.

In [59]:
tf.reduce_max(one_zero),tf.reduce_min(one_zero)

(<tf.Tensor: shape=(), dtype=float32, numpy=0.9999827146530151>,
 <tf.Tensor: shape=(), dtype=float32, numpy=1.7881393432617188e-06>)

In [60]:
one_zero = tf.constant(np.random.rand(224,224,3))

In [61]:
one_zero,one_zero

(<tf.Tensor: shape=(224, 224, 3), dtype=float64, numpy=
 array([[[0.93535597, 0.07582474, 0.86940044],
         [0.57647153, 0.54299029, 0.99770256],
         [0.98789557, 0.29645138, 0.65638303],
         ...,
         [0.03311104, 0.04020366, 0.68030179],
         [0.44719876, 0.1967414 , 0.63737346],
         [0.81867575, 0.17705667, 0.34416224]],
 
        [[0.2996718 , 0.79168127, 0.86635858],
         [0.60432549, 0.18758742, 0.04319499],
         [0.2559429 , 0.30191614, 0.13605943],
         ...,
         [0.64370182, 0.51265832, 0.8467124 ],
         [0.71044129, 0.0450956 , 0.11379651],
         [0.32864799, 0.30974445, 0.57284901]],
 
        [[0.57514962, 0.12502971, 0.34409547],
         [0.92833535, 0.41531598, 0.3640415 ],
         [0.88899352, 0.90040462, 0.52475232],
         ...,
         [0.80053741, 0.54375375, 0.47253708],
         [0.05621999, 0.09935329, 0.68344352],
         [0.32285399, 0.48209795, 0.08543375]],
 
        ...,
 
        [[0.7152964 , 0.01370969

##### 8 - Created a tensor with random values of shape [1, 224, 224, 3] then squeeze it to change the shape to [224, 224, 3].

In [72]:
rand_ten = tf.constant(np.random.randint(0,150529),
shape=(1,224,224,3))

In [76]:
tf.squeeze(rand_ten,axis=0)

<tf.Tensor: shape=(224, 224, 3), dtype=int32, numpy=
array([[[112285, 112285, 112285],
        [112285, 112285, 112285],
        [112285, 112285, 112285],
        ...,
        [112285, 112285, 112285],
        [112285, 112285, 112285],
        [112285, 112285, 112285]],

       [[112285, 112285, 112285],
        [112285, 112285, 112285],
        [112285, 112285, 112285],
        ...,
        [112285, 112285, 112285],
        [112285, 112285, 112285],
        [112285, 112285, 112285]],

       [[112285, 112285, 112285],
        [112285, 112285, 112285],
        [112285, 112285, 112285],
        ...,
        [112285, 112285, 112285],
        [112285, 112285, 112285],
        [112285, 112285, 112285]],

       ...,

       [[112285, 112285, 112285],
        [112285, 112285, 112285],
        [112285, 112285, 112285],
        ...,
        [112285, 112285, 112285],
        [112285, 112285, 112285],
        [112285, 112285, 112285]],

       [[112285, 112285, 112285],
        [112285, 112285,

In [68]:
tf.squeeze(rand_ten)

<tf.Tensor: shape=(223, 224, 3), dtype=float32, numpy=
array([[[0.4426198 , 0.05887794, 0.17908955],
        [0.7922437 , 0.8167697 , 0.41198957],
        [0.82260597, 0.53835225, 0.6133268 ],
        ...,
        [0.0757755 , 0.2795099 , 0.17868316],
        [0.3427136 , 0.3490343 , 0.5656855 ],
        [0.8444152 , 0.1985625 , 0.3354262 ]],

       [[0.41217065, 0.52971125, 0.22738314],
        [0.41531384, 0.93621993, 0.43685162],
        [0.66169584, 0.7332854 , 0.6243347 ],
        ...,
        [0.47276413, 0.30541122, 0.18355227],
        [0.07607555, 0.49983847, 0.07718766],
        [0.33159983, 0.74378073, 0.72005844]],

       [[0.20445907, 0.8577479 , 0.6865034 ],
        [0.74354196, 0.41980827, 0.90582204],
        [0.84128845, 0.30636716, 0.336856  ],
        ...,
        [0.27634883, 0.3217231 , 0.9086913 ],
        [0.883132  , 0.43129385, 0.4876827 ],
        [0.9256065 , 0.40351963, 0.47837806]],

       ...,

       [[0.85796773, 0.64242816, 0.4878044 ],
        [0.76

##### 9 - Create a tensor with shape [10] using your own choice of values, then find the index which has the maximum value.

In [107]:
val_10_tensor = tf.constant([1,2,3,4,5,6,7,8,9,10],shape=[10])

In [108]:
val_10_tensor

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int32)>

In [109]:
tf.argmax(val_10_tensor)

<tf.Tensor: shape=(), dtype=int64, numpy=9>

##### 10 - One-hot encode the tensor you created in 9.

In [113]:
tf.one_hot(val_10_tensor,depth=11)

<tf.Tensor: shape=(10, 11), dtype=float32, numpy=
array([[0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]], dtype=float32)>

# Extra Curriculum

- Go through the TensorFlow 2.x quick start for beginners tutorial (be sure to type out all of the code yourself, even if you don't understand it).

- Are there any functions we used in here that match what's used in there? Which are the same? Which haven't you seen before?

In [129]:
print(tf.__version__)

2.19.0


In [4]:
mnist = tf.keras.datasets.mnist

In [5]:
(x_train, y_train), (x_test, y_test) = mnist.load_data()

11490434/11490434 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step


In [6]:
x_train.shape

(60000, 28, 28)

In [7]:
x_test.shape

(10000, 28, 28)

In [8]:
y_train.shape

(60000,)

In [9]:
x_train[0][0]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0], dtype=uint8)

In [10]:
x_train, x_test = x_train / 255.0, x_test / 255.0

In [11]:
x_train[0][0]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [12]:
model = tf.keras.models.Sequential(
    [
        tf.keras.layers.Flatten(input_shape=(28,28)),
        tf.keras.layers.Dense(128, activation='relu'),
        tf.keras.layers.Dropout(0.2),
        tf.keras.layers.Dense(10)
    ]
)

/usr/local/lib/python3.12/dist-packages/keras/src/layers/reshaping/flatten.py:37: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


In [13]:
model

<Sequential name=sequential, built=True>

In [15]:
predictions = model(x_train[:1]).numpy()
predictions

array([[ 0.37124214, -0.03241861,  0.25215185,  0.0030393 , -0.14431074,
         0.48790717,  0.16903436, -0.21211654, -0.6760744 ,  0.04537279]],
      dtype=float32)

In [16]:
tf.nn.softmax(predictions).numpy()

array([[0.13483973, 0.0900555 , 0.11970096, 0.09330597, 0.08052229,
        0.1515252 , 0.11015397, 0.0752434 , 0.0473123 , 0.09734073]],
      dtype=float32)

In [17]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(
    from_logits=True
)

In [19]:
loss_fn(y_train[:1],predictions).numpy()

np.float32(1.8870034)

In [20]:
model.compile(
    optimizer='adam',
    loss=loss_fn,
    metrics=['accuracy']
)

In [21]:
model

<Sequential name=sequential, built=True>

In [24]:
model.fit(x_train, y_train, epochs=15)

Epoch 1/15
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.9811 - loss: 0.0590
Epoch 2/15
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.9833 - loss: 0.0502
Epoch 3/15
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.9846 - loss: 0.0468
Epoch 4/15
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - accuracy: 0.9855 - loss: 0.0429
Epoch 5/15
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.9881 - loss: 0.0374
Epoch 6/15
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.9888 - loss: 0.0364
Epoch 7/15
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.9877 - loss: 0.0356
Epoch 8/15
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.9894 - loss: 0.0317
Epoch 9/15
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.9894 - loss: 0.0298
Epoch 10/15
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.9900 - loss: 0.0294
Epoch 11/15
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.9900 - loss: 0.0288
Epoch 12/15
1875/1875 ━━━━━━━━

In [26]:
model.evaluate(x_test,y_test, verbose=2)

313/313 - 1s - 2ms/step - accuracy: 0.9795 - loss: 0.0802


[0.08017435669898987, 0.9794999957084656]

In [27]:
prob_model = tf.keras.Sequential([
    model, tf.keras.layers.Softmax()
])

In [29]:
prob_model(x_test[:1])

<tf.Tensor: shape=(1, 10), dtype=float32, numpy=
array([[1.1213134e-10, 2.0214712e-10, 7.1797253e-09, 1.1427572e-07,
        7.5752684e-19, 1.8824491e-12, 1.0912245e-20, 9.9999988e-01,
        4.5719023e-12, 1.6108077e-08]], dtype=float32)>